# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_id_jsons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('saveid', models.CharField(max_length=30)),
                ('json', models.TextField()),
            ],
        ),
    ]
