# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_id_jsons',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_id_jsons',
            name='saveid',
            field=models.CharField(max_length=30, primary_key=True),
        ),
        migrations.AlterField(
            model_name='user_id_jsons',
            name='user',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
