# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20170331_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_id_jsons',
            name='state',
            field=models.CharField(default='saved', max_length=30),
        ),
    ]
